CI: fix root module zip in nightly release

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -64,10 +64,16 @@ jobs:
           COMMITS=$(git log ${{ steps.fetch-tag.outputs.tag }}..HEAD --pretty=format:"- %s (%h)" --abbrev-commit)
           echo "::set-output name=commits::${COMMITS}"
       - name: Build and zip root-module
-        run: ./build-magisk-module.sh "../${{ env.APK_NAME }}.zip"
+        run: ./build-magisk-module.sh "${{ github.workspace }}/${{ env.APK_NAME }}.zip"
+      - name: Verify zip file exists
+        run: |
+          if [ ! -f "${{ github.workspace }}/${{ env.APK_NAME }}.zip" ]; then
+            echo "Error: Zip file not found!"
+            exit 1
+          fi
       - name: Delete release if exist then create release
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           gh release view "nightly" && gh release delete "nightly" -y --cleanup-tag
-          gh release create "nightly" "./$APK_NAME" "../${{ env.APK_NAME }}.zip" -p -t "Nightly Release" -n "${{ steps.get-commits.outputs.commits }}" --generate-notes
+          gh release create "nightly" "./$APK_NAME" "${{ github.workspace }}/${{ env.APK_NAME }}.zip" -p -t "Nightly Release" -n "${{ steps.get-commits.outputs.commits }}" --generate-notes
